//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationHub.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string ContentURL { get; set; }
        public Nullable<short> ContentTypeId { get; set; }
        public int UserId { get; set; }
        public int SharedBy { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
