//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationHub.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public long Id { get; set; }
        public int UserId { get; set; }
        public string Browser { get; set; }
        public string BrowserVersion { get; set; }
        public bool IsMobileDevice { get; set; }
        public System.DateTime LoggedOn { get; set; }
        public System.DateTime LastActivityOn { get; set; }
        public string IPAddress { get; set; }
    }
}
