//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2C.DataStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class C2CStoreEntities : DbContext
    {
        public C2CStoreEntities()
            : base("name=C2CStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BlogPost> BlogPosts { get; set; }
        public DbSet<BlogPostGroup> BlogPostGroups { get; set; }
        public DbSet<ContentComment> ContentComments { get; set; }
        public DbSet<ContentLike> ContentLikes { get; set; }
        public DbSet<ContentShare> ContentShares { get; set; }
        public DbSet<ContentSharedUser> ContentSharedUsers { get; set; }
        public DbSet<ContentType> ContentTypes { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<MetaMaster> MetaMasters { get; set; }
        public DbSet<MetaValue> MetaValues { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<Poll> Polls { get; set; }
        public DbSet<PollAnswer> PollAnswers { get; set; }
        public DbSet<PollGroup> PollGroups { get; set; }
        public DbSet<PollResult> PollResults { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<RolePermission> RolePermissions { get; set; }
        public DbSet<SiteSetting> SiteSettings { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserGroup> UserGroups { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<UserSetting> UserSettings { get; set; }
        public DbSet<WelcomeNote> WelcomeNotes { get; set; }
        public DbSet<Question> Questions { get; set; }
        public DbSet<QuestionAnswer> QuestionAnswers { get; set; }
        public DbSet<Quiz> Quizs { get; set; }
        public DbSet<QuizParticipant> QuizParticipants { get; set; }
        public DbSet<QuizParticipantsAnswer> QuizParticipantsAnswers { get; set; }
        public DbSet<QuizParticipantsSubjectiveAnswer> QuizParticipantsSubjectiveAnswers { get; set; }
        public DbSet<QuizQuestion> QuizQuestions { get; set; }
        public DbSet<QuizSchedule> QuizSchedules { get; set; }
        public DbSet<QuizScheduleGroup> QuizScheduleGroups { get; set; }
    }
}
