//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2C.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentLike
    {
        public int Id { get; set; }
        public int LikedBy { get; set; }
        public System.DateTime LikedOn { get; set; }
        public short ContentTypeId { get; set; }
        public int ContentId { get; set; }
    
        public virtual ContentType ContentType { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
