//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2C.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.BlogPostGroups = new HashSet<BlogPostGroup>();
            this.PollGroups = new HashSet<PollGroup>();
            this.UserGroups = new HashSet<UserGroup>();
            this.QuizScheduleGroups = new HashSet<QuizScheduleGroup>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsCollege { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual ICollection<BlogPostGroup> BlogPostGroups { get; set; }
        public virtual ICollection<PollGroup> PollGroups { get; set; }
        public virtual ICollection<UserGroup> UserGroups { get; set; }
        public virtual ICollection<QuizScheduleGroup> QuizScheduleGroups { get; set; }
    }
}
