//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2C.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaMaster
    {
        public MetaMaster()
        {
            this.MetaValues = new HashSet<MetaValue>();
        }
    
        public short Id { get; set; }
        public string KeyReference { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<MetaValue> MetaValues { get; set; }
    }
}
