//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2C.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poll
    {
        public Poll()
        {
            this.PollAnswers = new HashSet<PollAnswer>();
            this.PollGroups = new HashSet<PollGroup>();
            this.PollResults = new HashSet<PollResult>();
        }
    
        public int Id { get; set; }
        public string Question { get; set; }
        public System.DateTime VisibleFrom { get; set; }
        public System.DateTime VisibleTill { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte Status { get; set; }
        public bool Notify { get; set; }
    
        public virtual ICollection<PollAnswer> PollAnswers { get; set; }
        public virtual ICollection<PollGroup> PollGroups { get; set; }
        public virtual ICollection<PollResult> PollResults { get; set; }
    }
}
