//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2C.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizParticipant
    {
        public QuizParticipant()
        {
            this.QuizParticipantsAnswers = new HashSet<QuizParticipantsAnswer>();
            this.QuizParticipantsAnswers1 = new HashSet<QuizParticipantsAnswer>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int QuizScheduleId { get; set; }
        public int Score { get; set; }
        public System.DateTime LaunchedOn { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
        public byte Attempt { get; set; }
    
        public virtual QuizSchedule QuizSchedule { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<QuizParticipantsAnswer> QuizParticipantsAnswers { get; set; }
        public virtual ICollection<QuizParticipantsAnswer> QuizParticipantsAnswers1 { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
