//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2C.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizQuestion
    {
        public QuizQuestion()
        {
            this.QuizParticipantsAnswers = new HashSet<QuizParticipantsAnswer>();
        }
    
        public int Id { get; set; }
        public int QuizId { get; set; }
        public int QuestionId { get; set; }
        public int OrderId { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Quiz Quiz { get; set; }
        public virtual ICollection<QuizParticipantsAnswer> QuizParticipantsAnswers { get; set; }
    }
}
