//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2C.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizSchedule
    {
        public QuizSchedule()
        {
            this.QuizParticipants = new HashSet<QuizParticipant>();
            this.QuizScheduleGroups = new HashSet<QuizScheduleGroup>();
        }
    
        public int Id { get; set; }
        public int QuizId { get; set; }
        public System.DateTime VisibleFrom { get; set; }
        public System.DateTime VisibleTill { get; set; }
        public bool ShowResultOnCompletion { get; set; }
        public bool IsResultPublished { get; set; }
        public bool Notify { get; set; }
        public byte Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Quiz Quiz { get; set; }
        public virtual ICollection<QuizParticipant> QuizParticipants { get; set; }
        public virtual ICollection<QuizScheduleGroup> QuizScheduleGroups { get; set; }
    }
}
