//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2C.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteSetting
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public short Version { get; set; }
        public bool IsFederationEnabled { get; set; }
        public bool TranslateClaimsToUserProperties { get; set; }
        public bool TranslateClaimsToRoles { get; set; }
        public string StsIssuerUrl { get; set; }
        public string StsLoginUrl { get; set; }
        public string CtsLoginUrl { get; set; }
        public string Realm { get; set; }
        public string ReturnUrlBase { get; set; }
        public string AudienceUrl { get; set; }
        public string X509CertificateThumbprint { get; set; }
        public bool ModerateComment { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
