//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2C.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.QuizParticipants = new HashSet<QuizParticipant>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public byte RetryAttempt { get; set; }
        public Nullable<System.DateTime> LastLogon { get; set; }
        public Nullable<System.DateTime> LastBadLogon { get; set; }
        public Nullable<System.DateTime> AccountValidity { get; set; }
        public byte Status { get; set; }
        public bool IsLocked { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<QuizParticipant> QuizParticipants { get; set; }
    }
}
