//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2C.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.ContentComments = new HashSet<ContentComment>();
            this.ContentLikes = new HashSet<ContentLike>();
            this.ContentShares = new HashSet<ContentShare>();
            this.ContentSharedUsers = new HashSet<ContentSharedUser>();
            this.PollResults = new HashSet<PollResult>();
            this.UserGroups = new HashSet<UserGroup>();
            this.UserRoles = new HashSet<UserRole>();
            this.QuizParticipants = new HashSet<QuizParticipant>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<int> CollegeId { get; set; }
        public string ProfilePhoto { get; set; }
        public byte Status { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual ICollection<ContentComment> ContentComments { get; set; }
        public virtual ICollection<ContentLike> ContentLikes { get; set; }
        public virtual ICollection<ContentShare> ContentShares { get; set; }
        public virtual ICollection<ContentSharedUser> ContentSharedUsers { get; set; }
        public virtual ICollection<PollResult> PollResults { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<UserGroup> UserGroups { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual UserSetting UserSetting { get; set; }
        public virtual ICollection<QuizParticipant> QuizParticipants { get; set; }
    }
}
